version: '3'

services:
  btxcore:
    build:
      context: .
    ports:
      - 3001:3001
      - 8333:8333
    volumes:
      - /home/$USER/btxcore:/root/bitcore
    environment:
      - NETWORK=livenet
    restart: unless-stopped
